package:
  name: trivy
  version: 0.54.0
  epoch: 2
  description: Simple and comprehensive vulnerability scanner for containers
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os


pipeline:
  - uses: git-checkout
    with:
      expected-commit: ff403a3841b150d6366961e36604ade54f331790
      repository: https://github.com/aquasecurity/trivy
      tag: v${{package.version}}

  #  - uses: go/bump
    #  with:
      #  deps: google.golang.org/grpc@v1.64.1

  - uses: go/build
    with:
      packages: ./cmd/trivy
      output: trivy
      ldflags: -X github.com/aquasecurity/trivy/pkg/version/app.ver=${{package.version}}

test:
  environment:
    contents:
      packages:
        - jq
  pipeline:
    - name: Check trivy version
      runs: |
        trivy version
        trivy version | grep '^Version: ${{package.version}}$'
    - name: Check trivy version as JSON
      runs: |
        trivy version -f json | jq -M
        [ "$(trivy version -f json 2>/dev/null | jq -r .Version)" == "${{package.version}}" ]

update:
  enabled: true
  github:
    identifier: aquasecurity/trivy
    strip-prefix: v
